CREATE USER it4u_user WITH PASSWORD 'Geosoft@1234';
GRANT ALL PRIVILEGES ON DATABASE it4u TO it4u_user;
ALTER USER it4u_user CREATEDB;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO it4u_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO it4u_user;
GRANT ALL PRIVILEGES ON SCHEMA public TO it4u_user;
