--
-- PostgreSQL database dump
--


-- Dumped from database version 14.20
-- Dumped by pg_dump version 14.20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    id bigint NOT NULL,
    original_file_name character varying(255) NOT NULL,
    stored_file_name character varying(255) NOT NULL,
    content_type character varying(255),
    size_bytes bigint,
    sha256 character varying(255),
    uploaded_at timestamp(6) without time zone,
    deleted boolean NOT NULL DEFAULT false,
    ticket_id bigint NOT NULL,
    uploaded_by_id bigint
);


--
-- Name: attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    content character varying(1000) NOT NULL,
    created_at timestamp(6) without time zone,
    author_id bigint,
    ticket_id bigint NOT NULL
);


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_audit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_audit (
    id bigint NOT NULL,
    cc_email character varying(255),
    error_message text,
    event_type character varying(255) NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    subject character varying(255),
    ticket_id bigint,
    to_email character varying(255) NOT NULL,
    CONSTRAINT email_audit_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['TICKET_CREATED'::character varying, 'MANAGER_APPROVAL_REQUESTED'::character varying, 'MANAGER_APPROVED'::character varying, 'MANAGER_REJECTED'::character varying, 'ADMIN_STATUS_CHANGED'::character varying, 'TICKET_RESOLVED'::character varying, 'TICKET_CLOSED'::character varying, 'SMTP_TEST'::character varying])::text[])))
);


--
-- Name: email_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_base_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_base_articles (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    title character varying(255) NOT NULL,
    author_id bigint
);


--
-- Name: knowledge_base_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.knowledge_base_articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_base_articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: node_health_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.node_health_logs (
    id bigint NOT NULL,
    check_time timestamp(6) without time zone NOT NULL,
    checked_by character varying(255),
    details text,
    error_message character varying(255),
    response_time integer,
    status character varying(255) NOT NULL,
    service_node_id bigint NOT NULL
);


--
-- Name: node_health_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.node_health_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.node_health_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_nodes (
    id bigint NOT NULL,
    configuration text,
    created_at timestamp(6) without time zone,
    description character varying(255),
    environment character varying(255),
    health_check_interval integer,
    health_check_url text,
    health_status character varying(255),
    host_name character varying(255),
    ip_address character varying(255),
    last_health_check timestamp(6) without time zone,
    location character varying(255),
    name character varying(255) NOT NULL,
    node_id character varying(255) NOT NULL,
    node_type character varying(255) NOT NULL,
    owner character varying(255),
    port integer,
    status character varying(255) NOT NULL,
    team character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: service_nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service_nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(1000),
    device_details character varying(255),
    domain character varying(255),
    employee_id character varying(255),
    manager_approval_status character varying(255),
    manager_email character varying(255),
    manager_name character varying(255),
    new_user_details text,
    priority character varying(255),
    request_type character varying(255),
    sla_deadline timestamp(6) without time zone,
    sla_status character varying(255),
    software_name character varying(255),
    software_version character varying(255),
    status character varying(255),
    sub_category character varying(255),
    ticket_number character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    approved_at timestamp(6) without time zone,
    rejected_at timestamp(6) without time zone,
    in_progress_at timestamp(6) without time zone,
    resolved_at timestamp(6) without time zone,
    closed_at timestamp(6) without time zone,
    assigned_to_id bigint,
    requester_id bigint,
    manager_id bigint,
    CONSTRAINT tickets_category_check CHECK (((category)::text = ANY ((ARRAY['SOFTWARE'::character varying, 'HARDWARE'::character varying, 'ACCESS_AND_M365'::character varying, 'NETWORK'::character varying, 'ACCOUNT'::character varying, 'ENGINEERING_APP'::character varying, 'PROCUREMENT'::character varying, 'OTHERS'::character varying])::text[]))),
    CONSTRAINT tickets_manager_approval_status_check CHECK (((manager_approval_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'NA'::character varying])::text[]))),
    CONSTRAINT tickets_priority_check CHECK (((priority)::text = ANY (ARRAY['UNASSIGNED'::text, 'LOW'::text, 'MEDIUM'::text, 'HIGH'::text, 'CRITICAL'::text]))),
    CONSTRAINT tickets_sla_status_check CHECK (((sla_status)::text = ANY ((ARRAY['ON_TRACK'::character varying, 'AT_RISK'::character varying, 'BREACHED'::character varying])::text[]))),
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying, 'WAITING_FOR_USER'::character varying, 'PENDING_MANAGER_APPROVAL'::character varying])::text[])))
);


--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    department character varying(255),
    job_title character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    manager_id bigint,
    active boolean DEFAULT true NOT NULL,
    auth_provider character varying(255),
    created_by_admin boolean DEFAULT false NOT NULL,
    email character varying(255),
    phone_number character varying(255),
    full_name character varying(255),
    last_login_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['EMPLOYEE'::character varying, 'IT_SUPPORT'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying, 'SECURITY_TEAM'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: email_audit email_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_audit
    ADD CONSTRAINT email_audit_pkey PRIMARY KEY (id);


--
-- Name: knowledge_base_articles knowledge_base_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_base_articles
    ADD CONSTRAINT knowledge_base_articles_pkey PRIMARY KEY (id);


--
-- Name: node_health_logs node_health_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_health_logs
    ADD CONSTRAINT node_health_logs_pkey PRIMARY KEY (id);


--
-- Name: service_nodes service_nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_nodes
    ADD CONSTRAINT service_nodes_pkey PRIMARY KEY (id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: service_nodes ukfp4llckueuco9e465sq7u5f2y; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_nodes
    ADD CONSTRAINT ukfp4llckueuco9e465sq7u5f2y UNIQUE (node_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users fk5p1ci5btqfwvtaqx5n2wxi182; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk5p1ci5btqfwvtaqx5n2wxi182 FOREIGN KEY (manager_id) REFERENCES public.users(id);


--
-- Name: tickets fk5rh6sv173dg96qf8ba7vcmt91; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk5rh6sv173dg96qf8ba7vcmt91 FOREIGN KEY (manager_id) REFERENCES public.users(id);


--
-- Name: users fk_users_manager; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_manager FOREIGN KEY (manager_id) REFERENCES public.users(id);


--
-- Name: attachments fkay82o4g9v0hkdlh20yllwvutc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fkay82o4g9v0hkdlh20yllwvutc FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: knowledge_base_articles fkbjibe0is7whfham247cddboo6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_base_articles
    ADD CONSTRAINT fkbjibe0is7whfham247cddboo6 FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: tickets fkdp5i1hou98n2co3e49fffh9fp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkdp5i1hou98n2co3e49fffh9fp FOREIGN KEY (requester_id) REFERENCES public.users(id);


--
-- Name: comments fkj7vc0aigr2m5mew52v7ddt4fo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkj7vc0aigr2m5mew52v7ddt4fo FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: node_health_logs fkli8tf86t7xmms1485w9ujpgj3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_health_logs
    ADD CONSTRAINT fkli8tf86t7xmms1485w9ujpgj3 FOREIGN KEY (service_node_id) REFERENCES public.service_nodes(id);


--
-- Name: comments fkn2na60ukhs76ibtpt9burkm27; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkn2na60ukhs76ibtpt9burkm27 FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: tickets fkp0yqkqtkkwu2c92h784tfwf77; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkp0yqkqtkkwu2c92h784tfwf77 FOREIGN KEY (assigned_to_id) REFERENCES public.users(id);


--
-- Name: attachments fktj5qjndi69v9hltsn7q7ddx8g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fktj5qjndi69v9hltsn7q7ddx8g FOREIGN KEY (uploaded_by_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--


