import { test, expect } from '@playwright/test';

// Role credentials and landing pages
const ROLES = {
    EMPLOYEE: { user: 'employee_john', pass: 'password', landing: '/app/employee' },
    MANAGER: { user: 'manager_mike', pass: 'password', landing: '/app/manager' },
    IT_SUPPORT: { user: 'it_support_jane', pass: 'password', landing: '/app/it-support' },
    ADMIN: { user: 'admin', pass: 'password', landing: '/app/admin' } // Corrected landing for verification
};

async function loginAs(page, roleKey) {
    const { user, pass } = ROLES[roleKey];
    await page.goto('/login');
    await page.fill('input[name="username"]', user);
    await page.fill('input[name="password"]', pass);
    await page.click('button[type="submit"]');
    // Wait for redirect to app
    await page.waitForURL('**/app/**');
}

test.describe('Full E2E Regression (DEV + PROD)', () => {

    // 4.1 App Boot + SPA Fallback
    test('4.1 App Boot + SPA Fallback', async ({ page, context }) => {
        await context.clearCookies();
        // Open /app/employee directly
        await page.goto('/app/employee');
        try {
            await expect(page).toHaveURL(/(\/login|login\.microsoftonline\.com)/);
        } catch (e) {
            console.log('App Boot Check Failed. Current URL:', page.url());
            throw e;
        }

        // Check loading simple page
        await page.goto('/login');
        await expect(page.getByRole('heading', { name: /Sign in/i })).toBeVisible();
    });

    // 4.2 Legacy Redirects
    test('4.2 Legacy Redirects', async ({ page }) => {
        await loginAs(page, 'EMPLOYEE');
        await page.goto('/create');
        await expect(page).toHaveURL(/\/app\/tickets\/new/);
        await page.goto('/new-ticket');
        await expect(page).toHaveURL(/\/app\/tickets\/new/);
    });

    // 4.3 Auth Session + /api/auth/me behavior 
    test('4.3 Auth Session + /api/auth/me', async ({ page, request, context }) => {
        await context.clearCookies();
        await page.goto('/app');
        await expect(page).toHaveURL(/\/login/);

        const response = await request.get('/api/auth/me');
        if (response.status() === 200) {
            const url = response.url();
            console.log('Auth Me returned 200. URL:', url);
            if (!url.includes('/login') && !url.includes('oauth')) {
                const body = await response.text();
                if (!body.includes('Sign in') && !body.includes('IT4U')) {
                    expect(response.status()).toBe(401);
                }
            }
        } else {
            expect(response.status()).toBe(401);
        }
    });

    // 4.4 Role Routing
    for (const [key, data] of Object.entries(ROLES)) {
        test(`4.4 Role Routing - ${key}`, async ({ page }) => {
            await loginAs(page, key);
            await page.goto('/app');
            await expect(page).toHaveURL(new RegExp(data.landing));
            await expect(page.locator('table')).toBeVisible();
            await expect(page.getByText('Connection Error')).not.toBeVisible();
        });
    }

    // 4.5 Ticket Dashboard API Mapping
    test('4.5 Ticket Dashboard API Mapping (Manager)', async ({ page }) => {
        await loginAs(page, 'MANAGER');
        const approvalsReqPromise = page.waitForRequest(req => req.url().includes('/api/tickets/approvals') || req.url().includes('/api/tickets/my'));
        await page.goto('/app/manager');
        await approvalsReqPromise;
    });

    // 4.6 Ticket Creation Flow - EMPLOYEE
    test('4.6 Ticket Creation Flow - EMPLOYEE', async ({ page }) => {
        await loginAs(page, 'EMPLOYEE');
        await page.goto('/app/tickets/new');

        await page.fill('input[name="title"]', 'E2E Test Ticket ' + Date.now());
        await page.fill('textarea[name="description"]', 'Generated by Playwright');
        await page.selectOption('select[name="category"]', 'HARDWARE');

        await page.click('button[type="submit"]');

        await Promise.race([
            page.waitForURL(/\/app\/employee/),
            page.waitForSelector('text=Ticket created successfully', { timeout: 10000 }).catch(() => { })
        ]);

        if (page.url().includes('/app/employee')) {
            await expect(page).toHaveURL(/\/app\/employee/);
        } else {
            await expect(page.getByText('Ticket created successfully')).toBeVisible();
        }
    });

    // 4.7 Admin User Management UI
    test('4.7 Admin User Management UI', async ({ page }) => {
        await loginAs(page, 'ADMIN');
        await page.goto('/app/admin/users');
        await expect(page.locator('table')).toBeVisible();

        await page.setViewportSize({ width: 390, height: 844 });
        const editBtn = page.getByRole('button', { name: /edit/i }).first();
        if (await editBtn.count() > 0) {
            await expect(editBtn).toBeVisible();
        }
        await page.setViewportSize({ width: 1280, height: 720 });
    });

    // 4.8 Security Access Checks
    test('4.8 Security Access Checks', async ({ page }) => {
        await loginAs(page, 'EMPLOYEE');

        // Try to visit Admin Page
        await page.goto('/app/admin/users');

        // API interception for 403
        const response = await page.waitForResponse(resp => resp.url().includes('/api/users') && resp.status() === 403, { timeout: 5000 }).catch(() => null);

        if (!response) {
            // Fallback UI check
            if (page.url().includes('/app/admin/users')) {
                const rows = page.locator('tbody tr');
                expect(await rows.count()).toBe(0);
            } else {
                expect(page.url()).not.toContain('/app/admin/users');
            }
        } else {
            expect(response.status()).toBe(403);
        }
    });

});
